/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeAdbcConnection {
  createStatement(): _NativeAdbcStatement
  getObjects(opts: GetObjectsOptions): _NativeAdbcConnectionResultIterator
  getTableSchema(catalog: string | undefined | null, dbSchema: string | undefined | null, tableName: string): Buffer
  getTableTypes(): _NativeAdbcConnectionResultIterator
  getInfo(infoCodes?: Array<number> | undefined | null): _NativeAdbcConnectionResultIterator
}
export type _NativeAdbcConnection = NativeAdbcConnection

export declare class NativeAdbcConnectionResultIterator {
  next(): Promise<unknown>
}
export type _NativeAdbcConnectionResultIterator = NativeAdbcConnectionResultIterator

export declare class NativeAdbcDatabase {
  constructor(opts: ConnectOptions)
  connect(options?: Record<string, string> | undefined | null): _NativeAdbcConnection
}
export type _NativeAdbcDatabase = NativeAdbcDatabase

export declare class NativeAdbcStatement {
  setSqlQuery(query: string): void
  setOption(key: string, value: string): void
  executeQuery(): _NativeAdbcStatementIterator
  executeUpdate(): number
  bind(data: Buffer): void
}
export type _NativeAdbcStatement = NativeAdbcStatement

export declare class NativeAdbcStatementIterator {
  next(): Promise<unknown>
}
export type _NativeAdbcStatementIterator = NativeAdbcStatementIterator

export interface ConnectOptions {
  driver: string
  entrypoint?: string
  searchPaths?: Array<string>
  loadFlags?: number
  databaseOptions?: Record<string, string>
}

export declare function crateVersion(): string

export declare function defaultAdbcVersion(): string

export declare function defaultLoadFlags(): number

export interface GetObjectsOptions {
  depth: number
  catalog?: string
  dbSchema?: string
  tableName?: string
  tableType?: Array<string>
  columnName?: string
}
