/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeAdbcConnection {
  createStatement(): Promise<unknown>
  setOption(key: string, value: string): void
  getObjects(opts: GetObjectsOptions): Promise<unknown>
  getTableSchema(opts: GetTableSchemaOptions): Promise<unknown>
  getTableTypes(): Promise<unknown>
  getInfo(infoCodes?: Array<number> | undefined | null): Promise<unknown>
  commit(): Promise<unknown>
  rollback(): Promise<unknown>
  close(): void
}
export type _NativeAdbcConnection = NativeAdbcConnection

export declare class NativeAdbcConnectionResultIterator {
  next(): Promise<unknown>
  close(): void
}
export type _NativeAdbcConnectionResultIterator = NativeAdbcConnectionResultIterator

export declare class NativeAdbcDatabase {
  constructor(opts: ConnectOptions)
  connect(options?: Record<string, string> | undefined | null): Promise<unknown>
  close(): void
}
export type _NativeAdbcDatabase = NativeAdbcDatabase

export declare class NativeAdbcStatement {
  setSqlQuery(query: string): void
  setOption(key: string, value: string): void
  executeQuery(): Promise<unknown>
  executeUpdate(): Promise<unknown>
  bind(data: Buffer): Promise<unknown>
  close(): void
}
export type _NativeAdbcStatement = NativeAdbcStatement

export declare class NativeAdbcStatementIterator {
  next(): Promise<unknown>
  close(): void
}
export type _NativeAdbcStatementIterator = NativeAdbcStatementIterator

export interface ConnectOptions {
  driver: string
  entrypoint?: string
  searchPaths?: Array<string>
  loadFlags?: number
  databaseOptions?: Record<string, string>
}

export declare function crateVersion(): string

export declare function defaultAdbcVersion(): string

export declare function defaultLoadFlags(): number

export interface GetObjectsOptions {
  depth: number
  catalog?: string
  dbSchema?: string
  tableName?: string
  tableType?: Array<string>
  columnName?: string
}

export interface GetTableSchemaOptions {
  catalog?: string
  dbSchema?: string
  tableName: string
}

export interface QueryOptions {
  statementOptions?: Record<string, string>
}
