/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeAdbcConnection {
  createStatement(): _NativeAdbcStatement
}
export type _NativeAdbcConnection = NativeAdbcConnection

export declare class NativeAdbcDatabase {
  constructor(opts: ConnectOptions)
  connect(options?: Record<string, string> | undefined | null): _NativeAdbcConnection
}
export type _NativeAdbcDatabase = NativeAdbcDatabase

export declare class NativeAdbcStatement {
  setSqlQuery(query: string): void
  setOption(key: string, value: string): void
  executeQuery(): _NativeAdbcStatementIterator
  executeUpdate(): number
  bind(data: Buffer): void
}
export type _NativeAdbcStatement = NativeAdbcStatement

export declare class NativeAdbcStatementIterator {
  next(): Promise<unknown>
}
export type _NativeAdbcStatementIterator = NativeAdbcStatementIterator

export interface ConnectOptions {
  driver: string
  entrypoint?: string
  searchPaths?: Array<string>
  loadFlags?: number
  databaseOptions?: Record<string, string>
}

export declare function crateVersion(): string

export declare function defaultAdbcVersion(): string

export declare function defaultLoadFlags(): number
