/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AdbcConnection {
  statement(): AdbcStatement
}

export declare class AdbcDatabase {
  constructor(driver: string, entrypoint?: string | undefined | null)
  connection(): AdbcConnection
}

export declare class AdbcStatement {
  setSqlQuery(query: string): void
  execute(): number
}
